### ISSUE TITLE
DNS TXT records 0 record(s) found.

### ISSUE THREAD

**Issue by gas-limit** [Open-Attestation/toolkit#50]
I'm encountering a persistent issue where the OpenAttestation DNS TXT toolkit is not recognizing the DNS TXT records that I have configured. Despite trying with three separate domains, the problem remains. I am including the steps I took below:

- Issue: DNS TXT records not detected by OpenAttestation Toolkit.
- Affected domains: `dtgtest.gaslimit.engineer`, `docushield.live`, `dtgusa.org`
- Steps to reproduce:

1. Logged into the domain provider's management panel.
2. Navigated to the section to manage DNS settings.
3. Added a new TXT record with the values required by OpenAttestation.
4. Saved the changes and waited for the records to propagate (verified via a DNS lookup tool).
5. Attempted to use the OpenAttestation toolkit to validate the records.

- Expected result: The toolkit should recognize the TXT records.
- Actual result: The toolkit does not recognize the TXT records for any of the domains.

I have made sure that the TXT records are correctly formatted and have allowed sufficient time for DNS propagation. Attached are the screenshots of the DNS configurations for each domain as evidence of the setup.

Your guidance on this matter would be greatly appreciated as I'm unsure what might be going wrong.

Thank you for your time and help.

Docushield.live hosted on godaddy

![image](https://github.com/Open-Attestation/toolkit/assets/100609687/1579a14a-d52d-4c99-8141-6c18248d79b2)

dtgusa.org hosted on godaddy
![image](https://github.com/Open-Attestation/toolkit/assets/100609687/1f672978-f645-428b-a8b0-aca16ed2c19e)

deftest.gaslimit.engineer
![image](https://github.com/Open-Attestation/toolkit/assets/100609687/662e33ad-8811-4261-8346-82678cdc2b92)

**Comment by HJunyuan** [comment]
Hi @gas-limit, here are 2 observations made:

1. `docushield.live` TXT record contains an extra space (incorrect: `open atts`). Instead, it should start with `openatts`.
2. The `net=xxx` value should be `ethereum`.

As such, the TXT record should look something like this:
```txt
"openatts net=ethereum netId=51 addr=0xDD56dEeF360FBB1C18E703B26B790487b05c939A"
```

You can find more info on the DNS TXT record format here: https://www.openattestation.com/docs/developer-section/quickstart/configure-dns#inserting-the-dns-record-for-ethereum-smart-contracts

**Comment by gas-limit** [comment]
Hello @HJunyuan,

Thank you for your prompt assistance.

I've updated the DNS TXT record for `docushield.live` as follows, but it still isn't recognized by the OpenAttestation DNS lookup tool:

```
"openatts net=ethereum netId=51 addr=0xDD56dEeF360FBB1C18E703B26B790487b05c939A"
```

The Google DNS lookup yields the attached result, which appears correctly formatted.

![Google DNS Lookup Result](https://github.com/Open-Attestation/toolkit/assets/100609687/b8afa8b3-098c-4407-aa36-61ba31e5f05e)

[Google DNS Query Result](https://dns.google/query?name=docushield.live&rr_type=TXT&ecs=)

Could the contract itself influence how OpenAttestation processes the TXT record? I'm utilizing the TradeTrust Token contract from the token-registry repository as my document store. Here's the specific contract: [TradeTrust Token Contract](https://github.com/Open-Attestation/token-registry/blob/f9495dbb716e4a0a818bc08974c2d1efe84b0735/contracts/TradeTrustToken.sol).

Any further guidance on this would be greatly appreciated.

**Comment by HJunyuan** [comment]
@gas-limit We have just deployed a fix. Please try again and let us know. Thank you!

**Comment by gas-limit** [comment]
@HJunyuan

Thank you for the fix, it's working perfectly now!
